---
name: Check Commit Message

on:
  workflow_call:


jobs:
  validate-commit-message:
    name: Validate Commit Message
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
    steps:
      - name: Validate Commit Message Content
        uses: gsactions/commit-message-checker@b88ee88552f16f594ca19cb2c7fcd90df95c9bd4  # v1
        with:
          pattern: '^(#\d{3,6}|((Merge|dbeaver|cloudbeaver).+?#\d{3,6})|((DB-|CB-|web-)\d+)).*$'
          excludeDescription: 'true'
          excludeTitle: 'true'
          error: |
            Each commit message must begin with GitHub or Jira ticket reference. Like:
            *  #<issue_number>
            *  repo#<issue_number>
            *  org/repo#<issue_number>
            *  DB-Number (Jira)
            *  CB-Number (Jira)

            For how to rename your commit message, follow this GitHub Doc:
            https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message